class Chick
    def self.frame_one
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMhNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMmMMMMMMm+sMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMoNMMMMMs+oMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNs+ydNMMN+++MMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMdhdmho+oys+++mMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMMMMMMNy+++++dMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMmssmMMMMMMMNy++++++++yhmMMMMMMMMMM
        MMMMMMMNyhmMMMMMMNydNMMMMms+++yhmMNdy+++odMMMMMMMM
        MMMMMMMNmhssydNMMMMMMMMMy+shmMMMMMMMMMmhyyMMMMMMMM
        MMMMMMMMMMMmdysmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMhsssssssyMMMMMMMMMMMMMMMMMMMMMMo       /MMMMM
        MMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMNdysmMMMMMMMMMMMMMMMMMMd.:smMMMMMMMMMMM
        MMMMMMMMdhssydNMMMMMMMMMMMMMMMMMMMMNy/`.ohMMMMMMMM
        MMMMMMMNyhmNMMMMMNhdNMMMMMMMMMs+NMMMMMMho/mMMMMMMM
        MMMMMMMMMMMMMMMMmssdMMMMyyNMMMh:-dMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMMssNMMMMd:-hMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMMssNMMMMMm/-hMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMNmMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    
        ".colorize(:yellow)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_two
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMMMddMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMMssNMMMNmdyoyMMMMMMNyyMMMMM
        MMMMMMMMMMMMMMMmssmMMMMNssNMMMNmmd+oNMMMMho+dMMMMM
        MMMMMMMMMMMMMMMMmssmMMMMyyMMMMMMMMm++dMdo++dMMMMMM
        MMMMMMMNyhmMMMMMMNydNMMMMMMMMMMMMMMm++o+++dMMMMMMM
        MMMMMMMNmhssydNMMMMMMMMMMMMMmdhyso+++++++dMMMMMMMM
        MMMMMMMMMMMmdysmMMMMMMMMMMMMdhyyysssso+++mMMMMMMMM
        MMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMNo++hMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo++hMMMMMM
        MMMMMhsssssssyMMMMMMMMMMMMMMMMMMMMMMMMMMMy++NMMMMM
        MMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMNdysmMMMMMMMMMMMMMMMMMMm.:smMMMMMMMMMMM
        MMMMMMMMdhssydNMMMMMMMMMMMMMMMMMMMMNy/`.+dMMMMMMMM
        MMMMMMMNyhmNMMMMMNhdNMMMMMMMMMs/NMMMMMMdo/NMMMMMMM
        MMMMMMMMMMMMMMMMmssdMMMM+/MMMMh..mMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMM--MMMMMm.`hMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMM--MMMMMMN:`hMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMM--MMMMMMMNmMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMhhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM            
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.frame_three
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMNssNMMMMmssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMmssdMMMMyyNMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMNyhmMMMMMMNydNMMMMMMMMMdyNMMMMdhdhdhhMMMMMM
        MMMMMMMNmhssydNMMMMMMMMMMMMMMMMMMMMMMMNy+sNMMMMMMM
        MMMMMMMMMMMmdysmMMMMMMMMMMMMMMMMMMMMMMMh+yMMMMMMMM
        MMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMyoyhdmMMh+oMMNdhyso
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy++++oo++o++++sdN
        MMMMMhsssssssyMMMMMMMMMMMMMMMMMMMMMdy+++++++sdNMMM
        MMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMdo++dNMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs++MMMMMMMM
        MMMMMMMMMMMNdysmMMMMMMMMMMMMMMMMMMMMMMM+++MMMMMMMM
        MMMMMMMMdhssydNMMMMMMMMMMMMMMMMMMMMMMMM+++MMMMMMMM
        MMMMMMMNyhmNMMMMMm+sMMMMMMMMMMs+NMMMMMMmsdMMMMMMMM
        MMMMMMMMMMMMMMMMd:-hMMMM::MMMMd..mMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMh-:dMMMMM``MMMMMm.`dMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMh-:NMMMMMM``MMMMMMN-`dMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmNMMMMMMM``MMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMyyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.frame_four
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMNssNMMMMNssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMmssmMMMMyyMMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMNyhmMMMMMMNydNMMMMMMMMMdyNMMMMMMmhyNMMMMMMM
        MMMMMMMNmhssydNMMMMMMMMMMMMMMMMMMMMNdysshmNMMMMMMM
        MMMMMMMMMMMmdysmMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyNMMMMMMM
        MMMMMhsssssssyMMMMMMMMMMMMMMMMMMosmMMMMMMy+ohhmMMM
        MMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMm++sNMMMd+oNNMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+++yNy+oNMMMMMMM
        MMMMMMMMMMMds/-dMMMMMMMMMMMMMMMMMMmo+++++dmMMMMMMM
        MMMMMMMNho::+ymMMMMMMMMMMMMMMMMMMMMmo+++++++oosyhM
        MMMMMMMm+odNMMMMMN/sMMMMMMMMMMMMMMMh++syyhhhhdddmM
        MMMMMMMMMMMMMMMMm.`hMMMM::MMMMMMMMy++sMMMMMMMMMMMM
        MMMMMMMMMMMMMMMh..mMMMMM  MMMMMMMs++yMMMMMMMMMMMMM
        MMMMMMMMMMMMMMh`-NMMMMMM  MMMMMMm+ohMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmMMMMMMMM  MMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMyyMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.frame_five
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMNssNMMMMmssmMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMmssmMMMMyyNMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMNyhmMMMMMMNydNMMMMMMMMMdyNMMMMMMmhyNMMMMMMM
        MMMMMMMNmhssydNMMMMMMMMMMMMMMMMMMMMNdysshmNMMMMMMM
        MMMMMMMMMMMmdysmMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMM+-------sMMMMMMMMMMMMMMMMMMMMMMhssssssshMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMosMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMdo:`mMMMMMMMMMMMMMMm++NMMMMMddMMMMMMMMM
        MMMMMMMMh+-./ymMMMMMMMMMMMMMMMm++yMMMMMyoNMMMMMMMM
        MMMMMMMN:ohMMMMMMN+sMMMMMMMMMMh+++NNds+osohMMMMMMM
        MMMMMMMMMMMMMMMMm.`dMMMMMMMMMMy+++++ohmMMMNNMMMMMM
        MMMMMMMMMMMMMMMd`.mMMMMMMMMNdy+++++ohMMMMMMMMMMMMM
        MMMMMMMMMMMMMMd`:mMMMMMMNhs+++shyo+++ohNMMMMMMMMMM
        MMMMMMMMMMMMMMMNMMMMMMMm+++ydNMMMMNdhs++yNMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMMmhNMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.frame_six
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMNssNMMMMmssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMmssdMMMMyyNMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMm+ohMMMMMMNydNMMMMMMMMMdyNMMMMMMmhyNMMMMMMM
        MMMMMMMNho:-+ymMMMMMMMMMMMMMMMMMMMMNdysshmNMMMMMMM
        MMMMMMMMMMMms/-dMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMM+```````oMMMMMMMMMMMMMMMMMMMMMMhssssssshMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMms/.mMMMMMMMMMMMMddMMMMmsydmMMMMMMMMMMM
        MMMMMMMMd+.`/sNMMMMMMMMMMMNs+hMMMMMNdysshmMMMMMMMM
        MMMMMMMN:+dMMMMMMMMMMMMMMm++oMMMMMMMMMNmhymMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMy+++mMMMMMmNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmdhhhddds+++smmmmNhoNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMms++++++++++++oosssooNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMd+++oMMMMMNsmMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMNo++hMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMy++NMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMd+sMMMMMMMMMMMMMMMMMMMM          
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.frame_seven
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmNMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMh-/mMMMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMh--mMMMMNssNMMMMNssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMd:-hMMMMyyMMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMm/odMMMMMMm+sMMMMMMMMMMdyNMMMMMMmhyNMMMMMMM
        MMMMMMMMh+../yNMMMMMMMMMMMMMMMMMMMMNdysshmNMMMMMMM
        MMMMMMMMMMMms:.dMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMo       oMMMMMMMMMMMMMMMMMMMMMMhssssssshMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMhyhmMMMMMMMMMmhy+yMMMMMMMMMNdysshdMMMMMMMM
        MMMMMMMMdo+++ydNMmhs+++smMMMMMdyNMMMMMNmhyNMMMMMMM
        MMMMMMMMMMNhs++++++++ymMMMMMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMh+++++yNMMMMMMMMMmssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMN+++sho+ohmdhdMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMM/++mMMNds+oNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMs+sMMMMMM+NMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMs+dMMMMMMmMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM        
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.frame_eight
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMhhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmMMMMMMMM--MMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMh`-NMMMMMM--MMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMh..mMMMMM--MMMMMmssmMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMm.`dMMMM//MMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMN/odMMMMMMN/sMMMMMMMMMMdyNMMMMMMmhyNMMMMMMM
        MMMMMMMNh+.`/yNMMMMMMMMMMMMMMMMMMMMNdysshmNMMMMMMM
        MMMMMMMMMMMms:`mMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMM
        MMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMM++yMMMMMMMMMMMMMMMMMMMMMMMMMMMhssssssshMMMMM
        MMMMMMy++oNMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNMMMMM
        MMMMMMMd++oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMmo++ssssyyyyhdMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMd+++++++osyhdmMMMMMMMMMMMMMNdysshdMMMMMMMM
        MMMMMMMd+++o++dMMMMMMMMMMMMMMMdyNMMMMMNmhyNMMMMMMM
        MMMMMMm++ohMd++mMMMMMMMMyyNMMMmssmMMMMMMMMMMMMMMMM
        MMMMMm++hMMMMNoohmmNMMMMssNMMMMmssdMMMMMMMMMMMMMMM
        MMMMMyyNMMMMMMh+sdmNMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMmhMMMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                       
        ".colorize(:yellow)
        sleep (0.09)
        system 'clear'
    end

    def self.frame_nine
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMhhMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNMMMMMMMM``MMMMMMMNmMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMd`:NMMMMMM``MMMMMMm:-hMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMd`.mMMMMM``MMMMMd:-hMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMm.`dMMMM::MMMMd-:dMMMMMMMMMMMMMMMM
        MMMMMMMMdymMMMMMMN+sMMMMMMMMMMs+NMMMMMMmhyNMMMMMMM
        MMMMMMMM+++MMMMMMMMMMMMMMMMMMMMMMMMNdysshmNMMMMMMM
        MMMMMMMM++/MMMMMMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMM++oMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMM
        MMMMMMMd++odMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMdy+++++++ymMMMMMMMMMMMMMMMMMMMMMhssssssshMMMMM
        Mdy++++o++oo++++ymMMMMMMMMMMMMMMMMMMMNNNNNNNNMMMMM
        osyhdNMMs+hMMmdhssoMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMh+yMMMMMMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMNy+yNMMMMMMMMMMMMMMMMMMMMMMMNdysshmMMMMMMMM
        MMMMMMhydydydMMMMNhdNMMMMMMMMMdyNMMMMMNmhymMMMMMMM
        MMMMMMMMMMMMMMMMmssdMMMMyyNMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMMssNMMMMmssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMNssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMMssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM      
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.frame_ten
        puts "
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMddMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMNmMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsomMMMMMM  MMMMMMN:`hMMMMMMMMMMMMMM
        MMMMMMMMMMMMMy++sMMMMMMM  MMMMMm-.hMMMMMMMMMMMMMMM
        MMMMMMMMMMMMs++yMMMMMMMM::MMMMh.-dMMMMMMMMMMMMMMMM
        MNddddhhhyys++hMMMMMMMMMMMMMMMs/mMMMMMMdo+mMMMMMMM
        Mhyso+++++++++mMMMMMMMMMMMMMMMMMMMMmy+-:ohNMMMMMMM
        MMMMMMMNd++++++mMMMMMMMMMMMMMMMMMMd:/sdMMMMMMMMMMM
        MMMMMMMNo+yNy+++mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMmo+dMMMms++mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMmhyo+yMMMMMMNssMMMMMMMMMMMMMMMMMMhssssssshMMMMM
        MMMMMMMNydMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMNdysmMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        MMMMMMMMdhssydNMMMMMMMMMMMMMMMMMMMMNdysshdMMMMMMMM
        MMMMMMMNyhmNMMMMMNhdNMMMMMMMMMdyNMMMMMNmhyNMMMMMMM
        MMMMMMMMMMMMMMMMmssdMMMMyyNMMMmssmMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMmssmMMMMMssNMMMMmssdMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMdsyNMMMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     
        ".colorize(:yellow)
                                 sleep (0.09)
                                 system 'clear'
    end

    def self.animation
        3.times do
            Chick.frame_one
            Chick.frame_two
            Chick.frame_three
            Chick.frame_four
            Chick.frame_five
            Chick.frame_six
            Chick.frame_seven
            Chick.frame_eight
            Chick.frame_nine
            Chick.frame_ten
        end
    end

    def self.go
        system 'clear'
        self.animation
        puts ""
        # puts "
        # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMMMMMMMMMMddMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMMMMMMMMMM  MMMMMMMNmMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMdsomMMMMMM  MMMMMMN:`hMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMy++sMMMMMMM  MMMMMm-.hMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMs++yMMMMMMMM::MMMMh.-dMMMMMMMMMMMMMMMM
        # MNddddhhhyys++hMMMMMMMMMMMMMMMs/mMMMMMMdo+mMMMMMMM
        # Mhyso+++++++++mMMMMMMMMMMMMMMMMMMMMmy+-:ohNMMMMMMM
        # MMMMMMMNd++++++mMMMMMMMMMMMMMMMMMMd:/sdMMMMMMMMMMM
        # MMMMMMMNo+yNy+++mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMMMMmo+dMMMms++mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMmhyo+yMMMMMMNssMMMMMMMMMMMMMMMMMMhssssssshMMMMM
        # MMMMMMMNydMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMM
        # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMMMMMMMMMNdysmMMMMMMMMMMMMMMMMMMmsydmMMMMMMMMMMM
        # MMMMMMMMdhssydNMMMMMMMMMMMMMMMMMMMMNdysshdMMMMMMMM
        # MMMMMMMNyhmNMMMMMNhdNMMMMMMMMMdyNMMMMMNmhyNMMMMMMM
        # MMMMMMMMMMMMMMMMmssdMMMMyyNMMMmssmMMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMmssmMMMMMssNMMMMmssdMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMdsyNMMMMMMssNMMMMMNysdMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMNNMMMMMMNssNMMMMMMMNMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMMMMMMMMMMmmMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
        # MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     
        # ".colorize(:yellow)
    end
end